# Generated by Django 4.1.1 on 2022-10-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('cars_owned', models.ManyToManyField(to='car.car')),
            ],
        ),
    ]
